// import { getAllBgImages } from './utils.js'

export function injectedParserTask(options) {
/**
 * 论坛配置项
 */
const SELECTORS = {
  TITLE_MAIN: '#threadtitle h1',
  TITLE_NAV: '#nav',
  POST_MAIN: '.t_msgfontfix',
  POST_FIRST: '.postmessage.firstpost',
  POST_DEFAULT: '.defaultpost',
  POST_WRAP: 'wrap',
  AUTHOR_LINK: '.authorinfo .posterlink',
};

const INVALID_FILENAMES = new Set(['back.gif', 'none.gif', 'none.png', 'none.jpg', 'none.jpeg', 'none.webp']);

/**
 * 帖子解析器类 (TopicParser)
 */
class TopicParser {
  constructor(options = {}) {
    this.tid = options.tid;
    this.page = options.page ?? 1;
    this.allPage = !!options.allPage;
    this.currentUrl = window.location.href;
    this.origin = window.location.origin;
  }

  /**
   * 外部统一调用入口
   */
  execute() {
    const topicDom = this.parseTopicDom();

    // 权限不足或未找到核心 DOM
    if (!topicDom) {
      return {
        title: document.title,
        topic: undefined,
        url: this.currentUrl,
      };
    }

    return {
      title: this.parseTitle(),
      topic: this._buildTopicHtml(topicDom),
      author: this.parseAuthor(),
      authorLink: this.parseAuthorLink(),
      images: this.parseImages(topicDom),
      url: this.currentUrl,
      tid: this.tid,
      page: this.page,
    };
  }

  /**
   * 提取标题 (内部方法)
   */
  parseTitle() {
    return document.querySelector(SELECTORS.TITLE_MAIN)?.innerText
      || document.querySelector(SELECTORS.TITLE_NAV)?.innerText?.split('» ').at(-1)
      || '';
  }

  /**
   * 提取帖子核心 DOM 节点
   */
  parseTopicDom() {
    if (this.allPage) {
      return document.getElementById(SELECTORS.POST_WRAP);
    }
    return document.querySelector(SELECTORS.POST_MAIN)
      || document.querySelector(SELECTORS.POST_FIRST)
      || document.querySelector(SELECTORS.POST_DEFAULT);
  }

  /**
   * 提取作者名称
   */
  parseAuthor() {
    return document.querySelector(SELECTORS.AUTHOR_LINK)?.innerText?.trim() || '';
  }

  /**
   * 提取并拼接完整的作者主页链接
   */
  parseAuthorLink() {
    const href = document.querySelector(SELECTORS.AUTHOR_LINK)?.getAttribute('href');
    if (!href) return '';
    return href.startsWith('http') ? href : `${this.origin}/${href}`;
  }

  /**
   * 组装最终的主题 HTML
   */
  _buildTopicHtml(topicDom) {
    // 定义要插入的自定义 HTML 注释
    const date = new Date();
    const timestamp = new Intl.DateTimeFormat('zh-CN', { dateStyle: 'short', timeStyle: 'medium' }).format(date);
    const customComment = `\n<!-- Generated by TopicParser | Page: ${this.page} | Time: ${timestamp} -->\n`;

    if (this.allPage) {
      const navHtml = document.querySelector(SELECTORS.TITLE_NAV)?.outerHTML || '';
      return customComment + navHtml + topicDom.outerHTML;
    }
    return customComment + topicDom.outerHTML;
  }

  /**
   * 提取并过滤图片
   */
  parseImages(topicDom) {
    if (!topicDom) return [];
    
    return Array.from(topicDom.querySelectorAll('img'))
      .map(img => {
        const src = img.getAttribute('src');
        // 特殊逻辑：如果是占位图且存在 file 属性，则取 file 属性
        if (src?.endsWith('none.gif') && img.getAttribute('file')) {
          return img.getAttribute('file');
        }
        return src;
      })
      .filter(src => this._isValidImage(src));
  }

  /**
   * 校验图片 URL 是否有效
   */
  _isValidImage(src) {
    if (!src || !src.startsWith('http')) return false;
    
    // 提取文件名
    const pathPart = src.trim().split(/[?#]/)[0];
    const filename = pathPart.split('/').pop();
    
    return !INVALID_FILENAMES.has(filename);
  }
}

  return new TopicParser(options).execute();
}


/**
 * 保持原有的函数导出，内部转交给类处理
 */
// export function getTopicDetail(options) {
//   return new TopicParser(options).execute();
// }

export function getSearchpost() {
  const link = document.querySelector("#profile_act > li.searchpost > a");
  const name = document.querySelector("#profilecontent > div.itemtitle.s_clear > h1");

  const href = link?.getAttribute('href') || '';
  const url = href.startsWith('http') ? href : `${window.location.origin}/${href}`

  return {
    name: name.innerText || '',
    original: url,
    url: href.startsWith('/') ? href : `/${href}`
  }
}
